default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dont_forget_development

test:
  <<: *default
  database: dont_forget_test

production:
  <<: *default
  database: dont_forget_production
  username: dont_forget
  password: <%= ENV['DONTFORGET_DATABASE_PASSWORD'] %>
